name: test-tags

on:
  push:
    tags:
      - dev-**
      - prod-**

jobs:
  my-job-dev:
#    if: contains('refs/tags/dev', github.ref)
    runs-on: ubuntu-latest
    steps:
      - name: my-step-dev
        run: |
          echo "Hello DEV!"
          echo "${{ github.ref }}"
  my-job-prod:
    if: contains('refs/tags/prod', github.ref)
    runs-on: ubuntu-latest
    steps:
      - name: my-step-prod
        run: |
          echo "Hello PROD!"
          echo "${{ github.ref }}"
