name: test-tags

on:
  push:
    tags:
      - dev-**
      - prod-**

jobs:
  my-job-dev:
    if:
      contains('
        refs/heads/dev
      ', github.ref)
    runs-on: ubuntu-latest
    steps:
      - name: my-step-dev
        run: echo "Hello DEV!"
  my-job-prod:
    if:
      contains('
        refs/heads/dev
      ', github.ref)
    runs-on: ubuntu-latest
    steps:
      - name: my-step-prod
        run: echo "Hello PROD!"
